const blogs = [
    {
        title: "Lorem ipsum dolor sit amet, conse ctet uradipiscing elit.",
        story: "Sit amet consecteturad elit",
        plot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra",
        detailedPlot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra elementum Sed  accumsan nulla velit, vel imperdiet mi euismod eget. Nun",
        author:"",
        imagePath: "assets/Blog/blog1.png",
    },
    {
        title: "Lorem ipsum dolor sit amet, conse ctet uradipiscing elit.",
        story: "Sit amet consecteturad elit",
        plot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra",
        detailedPlot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra elementum Sed  accumsan nulla velit, vel imperdiet mi euismod eget. Nun",
        author:"",
        imagePath: "assets/Blog/blog2.png",
    },
    {
        title: "Lorem ipsum dolor sit amet, conse ctet uradipiscing elit.",
        story: "Sit amet consecteturad elit",
        plot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra",
        detailedPlot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra elementum Sed  accumsan nulla velit, vel imperdiet mi euismod eget. Nun",
        author:"",
        imagePath: "assets/Blog/blog3.png",
    },
    {
        title: "Lorem ipsum dolor sit amet, conse ctet uradipiscing elit.",
        story: "Sit amet consecteturad elit",
        plot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra",
        detailedPlot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra elementum Sed  accumsan nulla velit, vel imperdiet mi euismod eget. Nun",
        author:"",
        imagePath: "assets/Blog/blog1.png",
    },
    {
        title: "Lorem ipsum dolor sit amet, conse ctet uradipiscing elit.",
        story: "Sit amet consecteturad elit",
        plot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra",
        detailedPlot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra elementum Sed  accumsan nulla velit, vel imperdiet mi euismod eget. Nun",
        author:"",
        imagePath: "assets/Blog/blog2.png",
    },
    {
        title: "Lorem ipsum dolor sit amet, conse ctet uradipiscing elit.",
        story: "Sit amet consecteturad elit",
        plot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra",
        detailedPlot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra elementum Sed  accumsan nulla velit, vel imperdiet mi euismod eget. Nun",
        author:"",
        imagePath: "assets/Blog/blog3.png",
    },
    {
        title: "Lorem ipsum dolor sit amet, conse ctet uradipiscing elit.",
        story: "Sit amet consecteturad elit",
        plot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra",
        detailedPlot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra elementum Sed  accumsan nulla velit, vel imperdiet mi euismod eget. Nun",
        author:"",
        imagePath: "assets/Blog/blog1.png",
    },
    {
        title: "Lorem ipsum dolor sit amet, conse ctet uradipiscing elit.",
        story: "Sit amet consecteturad elit",
        plot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra",
        detailedPlot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra elementum Sed  accumsan nulla velit, vel imperdiet mi euismod eget. Nun",
        author:"",
        imagePath: "assets/Blog/blog2.png",
    },
    {
        title: "Lorem ipsum dolor sit amet, conse ctet uradipiscing elit.",
        story: "Sit amet consecteturad elit",
        plot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra",
        detailedPlot:"Lorem ipsum dolor sit amet, conse ctet uradipiscing elit. Etiam quis sapien vitaemauris interdum elementum Sed accumsan nulla velit, vel imperdiet mi euismod eget. Nunc viverra elementum Sed  accumsan nulla velit, vel imperdiet mi euismod eget. Nun",
        author:"",
        imagePath: "assets/Blog/blog3.png",
    },
]

export default blogs;